<a href="https://colab.research.google.com/github/rochactivo-UPC/elasticitat/blob/main/Ejercicios_Tema_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Solucion de Ejercicios del Tema 1

#1) Dados los vectores ***u***, ***v*** y ***w*** realizar las siguientes operaciones:





In [ ]:
import numpy as np

# Definición de los vectores
u = np.array([3, 2, -1])
v = np.array([-2, 4, 5])
w = np.array([1, 0, 0.5])

# a) u ⊗ v (Producto tensorial)
tensor_uv = np.outer(u, v)

# b) v ⊗ u (Producto tensorial)
tensor_vu = np.outer(v, u)

# c) u ⊗ w (Producto tensorial)
tensor_uw = np.outer(u, w)

# d) w ⊗ v (Producto tensorial)
tensor_wv = np.outer(w, v)

# e) (u ⊗ v) ⋅ w (Producto punto entre el producto tensorial y w)
dot_uv_w = np.dot(tensor_uv, w)

# f) (v ⊗ w) ⋅ u (Producto punto entre el producto tensorial y u)
dot_vw_u = np.dot(tensor_vu, w)

resultados = {
    "a": tensor_uv,
    "b": tensor_vu,
    "c": tensor_uw,
    "d": tensor_wv,
    "e": dot_uv_w,
    "f": dot_vw_u
}

resultados

{'a': array([[-6, 12, 15],
        [-4,  8, 10],
        [ 2, -4, -5]]),
 'b': array([[-6, -4,  2],
        [12,  8, -4],
        [15, 10, -5]]),
 'c': array([[ 3. ,  0. ,  1.5],
        [ 2. ,  0. ,  1. ],
        [-1. , -0. , -0.5]]),
 'd': array([[-2. ,  4. ,  5. ],
        [-0. ,  0. ,  0. ],
        [-1. ,  2. ,  2.5]]),
 'e': array([ 1.5,  1. , -0.5]),
 'f': array([-5. , 10. , 12.5])}

#3  Dados los tensores de segundo orden A, B y C realizar las siguientes operaciones:


In [ ]:
# Definición de los tensores de segundo orden A, B y C como matrices
A = np.array([[3, 0, 0],
              [0, 2, -1],
              [0, 0, 5]])

B = np.array([[0, 0, 4],
              [0, 6, 0],
              [0, -3, 1]])

C = np.array([[1, -2, 0],
              [0, 0, 4],
              [0, -6, 0]])

# a) A ⋅ B (Producto de matrices)
product_AB = np.dot(A, B)

# b) B ⋅ A (Producto de matrices)
product_BA = np.dot(B, A)

# c) A ⋅ C (Producto de matrices)
product_AC = np.dot(A, C)

# d) (A ⋅ B) ⋅ C (Producto de matrices)
product_ABC = np.dot(product_AB, C)

resultados_tensors = {
    "a": product_AB,
    "b": product_BA,
    "c": product_AC,
    "d": product_ABC
}

resultados_tensors

{'a': array([[  0,   0,  12],
        [  0,  15,  -1],
        [  0, -15,   5]]),
 'b': array([[ 0,  0, 20],
        [ 0, 12, -6],
        [ 0, -6,  8]]),
 'c': array([[  3,  -6,   0],
        [  0,   6,   8],
        [  0, -30,   0]]),
 'd': array([[  0, -72,   0],
        [  0,   6,  60],
        [  0, -30, -60]])}

In [ ]:
# Re-defining the tensors (matrices) A, B, C, and vectors v and w

# Vectors v and w
v = np.array([2, -3, 4])
w = np.array([4, 5, -1])

# a) (B ⋅ C) ⋅ v
product_BC_v = np.dot(np.dot(B, C), v)

# b) (A ⋅ C) ⋅ w
product_AC_w = np.dot(np.dot(A, C), w)

# For double product or double contraction, we perform tensor dot which calculates the sum over all the dimensions of the product.
# In matrix terms, it's equivalent to the sum of the product of corresponding elements.

# c) A:B (Double product or contraction)
double_product_AB = np.tensordot(A, B, axes=2)

# d) B:A (Double product or contraction)
double_product_BA = np.tensordot(B, A, axes=2)

resultados_nuevos = {
    "a": product_BC_v,
    "b": product_AC_w,
    "c": double_product_AB,
    "d": double_product_BA
}

resultados_nuevos

{'a': array([ 72,  96, -30]),
 'b': array([ -18,   22, -150]),
 'c': array(17),
 'd': array(17)}

Definición de una funcion para multiplicacion de tensores con notación indicial

In [ ]:
def matrix_product(V, B):

    m, n_V = V.shape
    n_B, p = B.shape
    if n_V != n_B:
        raise ValueError("El número de columnas de V debe de ser igual al número de filas de B")

    # Initialize the result matrix with zeros
    result = np.zeros((m, p))

    # Calculate the matrix product using nested for loops
    for i in range(m):
        for j in range(p):
            for k in range(n_V):
                result[i][j] += V[i][k] * B[k][j]

    return result

Comprobación de la función

In [ ]:
product_AB = np.dot(A, B)
print(product_AB)

[[  0   0  12]
 [  0  15  -1]
 [  0 -15   5]]


In [ ]:
product_AB_1 = matrix_product(A, B)
print(product_AB_1)

[[  0.   0.  12.]
 [  0.  15.  -1.]
 [  0. -15.   5.]]
